import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: 'jobs',
    title: 'Jobs',
    iconType: 'feather',
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'manage-coins',
    title: 'Manage Wallet',
    iconType: 'feather',
    icon: 'alert-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'reports',
    title: 'Reports',
    iconType: 'feather',
    icon: 'layout',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
